// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0iYTK25voJtRNqJ8bOTnKgX2JQkB7-RY',
    appId: '1:413461348289:web:0e8badff8dc6fa7530b940',
    messagingSenderId: '413461348289',
    projectId: 'cravecrush-a8ced',
    authDomain: 'cravecrush-a8ced.firebaseapp.com',
    storageBucket: 'cravecrush-a8ced.appspot.com',
    measurementId: 'G-JGPGEM8969',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBu2QhV1F02oNc9tAk-bB2YJoG87WgUOo',
    appId: '1:413461348289:android:5f6f5b1ebcd2b6e230b940',
    messagingSenderId: '413461348289',
    projectId: 'cravecrush-a8ced',
    storageBucket: 'cravecrush-a8ced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWKI4cGbPJ93IFLnueo-H2lhRNy7paoZY',
    appId: '1:413461348289:ios:0084f56c97c9f61830b940',
    messagingSenderId: '413461348289',
    projectId: 'cravecrush-a8ced',
    storageBucket: 'cravecrush-a8ced.appspot.com',
    iosBundleId: 'com.example.cravecrush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWKI4cGbPJ93IFLnueo-H2lhRNy7paoZY',
    appId: '1:413461348289:ios:0084f56c97c9f61830b940',
    messagingSenderId: '413461348289',
    projectId: 'cravecrush-a8ced',
    storageBucket: 'cravecrush-a8ced.appspot.com',
    iosBundleId: 'com.example.cravecrush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0iYTK25voJtRNqJ8bOTnKgX2JQkB7-RY',
    appId: '1:413461348289:web:c53d1ba636771ef630b940',
    messagingSenderId: '413461348289',
    projectId: 'cravecrush-a8ced',
    authDomain: 'cravecrush-a8ced.firebaseapp.com',
    storageBucket: 'cravecrush-a8ced.appspot.com',
    measurementId: 'G-XDP10PLWFJ',
  );
}
